# Separate pipeline from normal integration CI to allow branches to change legs

# Branches that trigger a build on commit
trigger:
- main
- main-vs-deps
- release/*
- features/*
- demos/*

# Branches that are allowed to trigger a build via /azp run.
# Automatic building of all PRs is disabled in the pipeline's trigger page.
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#comment-triggers
pr:
- main
- main-vs-deps
- release/*
- features/*
- demos/*

jobs:
- job: VS_Integration_LSP
  pool:
    name: NetCore1ESPool-Public
    demands: ImageOverride -equals $(queueName)
  timeoutInMinutes: 135

  steps:
    - template: eng/pipelines/test-integration-job.yml
      parameters:
        configuration: Debug
        oop64bit: true
        lspEditor: true
