name: CI

on:
  push:
    branches:
      - main
      - validate/*
  pull_request:

env:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BUILDCONFIGURATION: Release
  codecov_token: 4dc9e7e2-6b01-4932-a180-847b52b43d35 # Get a new one from https://codecov.io/
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages/

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-20.04
        - macos-latest
        - windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Install prerequisites
      run: |
        ./init.ps1 -UpgradePrerequisites
        dotnet --info

        # Print mono version if it is present.
        if (Get-Command mono -ErrorAction SilentlyContinue) {
          mono --version
        }
      shell: pwsh
    - name: Set pipeline variables based on source
      run: azure-pipelines/variables/_pipelines.ps1
      shell: pwsh
    - name: build
      run: dotnet build -t:build,pack --no-restore -c ${{ env.BUILDCONFIGURATION }} /v:m /bl:"${{ runner.temp }}/_artifacts/build_logs/build.binlog"
    - name: test
      run: azure-pipelines/dotnet-test-cloud.ps1 -Configuration ${{ env.BUILDCONFIGURATION }} -Agent ${{ runner.os }}
      shell: pwsh
    - name: Update pipeline variables based on build outputs
      run: azure-pipelines/variables/_pipelines.ps1
      shell: pwsh
    - name: Collect artifacts
      run: azure-pipelines/artifacts/_stage_all.ps1
      shell: pwsh
      if: always()
    - name: Upload project.assets.json files
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: projectAssetsJson-${{ runner.os }}
        path: ${{ runner.temp }}/_artifacts/projectAssetsJson
      continue-on-error: true
    - name: Upload variables
      uses: actions/upload-artifact@v1
      with:
        name: variables-${{ runner.os }}
        path: ${{ runner.temp }}/_artifacts/Variables
      continue-on-error: true
    - name: Upload build_logs
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: build_logs-${{ runner.os }}
        path: ${{ runner.temp }}/_artifacts/build_logs
      continue-on-error: true
    - name: Upload test_logs
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: test_logs-${{ runner.os }}
        path: ${{ runner.temp }}/_artifacts/test_logs
      continue-on-error: true
    - name: Upload testResults
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: testResults-${{ runner.os }}
        path: ${{ runner.temp }}/_artifacts/testResults
      continue-on-error: true
    - name: Upload coverageResults
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: coverageResults-${{ runner.os }}
        path: ${{ runner.temp }}/_artifacts/coverageResults
      continue-on-error: true
    - name: Upload symbols
      uses: actions/upload-artifact@v1
      with:
        name: symbols-${{ runner.os }}
        path: ${{ runner.temp }}/_artifacts/symbols
      continue-on-error: true
    - name: Upload deployables
      uses: actions/upload-artifact@v1
      with:
        name: deployables-${{ runner.os }}
        path: ${{ runner.temp }}/_artifacts/deployables
      if: always()
    - name: Publish code coverage results to codecov.io
      run: bash <(curl -s https://codecov.io/bash)
      shell: bash
      timeout-minutes: 3
      continue-on-error: true
