# See https://github.com/dotnet/arcade/blob/e52018a/Documentation/Maestro/New-Inter-Branch-Merge-Approach.md

name: Inter-branch merge
on:
  schedule:
    # Create a merge every 3 hours (works only for merges from `main`, others would need a `push` trigger).
    - cron: '0 */3 * * *'
  workflow_dispatch:
    inputs:
      configuration_file_branch:
        description: 'Branch to use for configuration file'
        required: true
        default: 'main'

permissions:
  contents: write
  pull-requests: write

jobs:
  # The config does not support multiple flows from the same source branch,
  # so we need to run separately for each duplicate source branch (https://github.com/dotnet/arcade/issues/15586).
  merge:
    if: github.repository == 'dotnet/roslyn'
    uses: dotnet/arcade/.github/workflows/inter-branch-merge-base.yml@main
    with:
      configuration_file_path: 'eng/config/branch-merge.jsonc'
      configuration_file_branch: ${{ inputs.configuration_file_branch || 'main' }}
  merge-2:
    if: github.repository == 'dotnet/roslyn'
    uses: dotnet/arcade/.github/workflows/inter-branch-merge-base.yml@main
    with:
      configuration_file_path: 'eng/config/branch-merge-2.jsonc'
      configuration_file_branch: ${{ inputs.configuration_file_branch || 'main' }}
