parameters:
- name: Is1ESPT
  type: boolean
- name: RealSign
  type: boolean
  default: false
- name: windowsPool
  type: object
  default:
    vmImage: windows-2022
- name: linuxPool
  type: object
  default:
    vmImage: ubuntu-20.04
- name: macOSPool
  type: object
  default:
    vmImage: macOS-12
- name: EnableLinuxBuild
  type: boolean
  default: true
- name: EnableMacOSBuild
  type: boolean
  default: true
- name: EnableOptProf
  type: boolean
  default: false
- name: IsOptProf
  type: boolean
  default: false
- name: ShouldSkipOptimize
  type: boolean
  default: false
- name: RunTests
  type: boolean
  default: true
- name: EnableLocalization
  type: boolean
  default: false
- name: EnableCompliance
  type: boolean
  default: false
- name: EnableAPIScan
  type: boolean
  default: false
- name: EnableDotNetFormatCheck
  type: boolean
  default: true
- name: artifact_names
  type: object
  default:
  - build_logs
  - coverageResults
  - deployables
  - projectAssetsJson
  - symbols
  - testResults
  - test_symbols
  - Variables

jobs:
- job: Windows
  pool: ${{ parameters.windowsPool }}
  timeoutInMinutes: 180 # Give plenty of time due to real signing
  ${{ if eq(variables['system.collectionId'], '011b8bdf-6d56-4f87-be0d-0092136884d9') }}:
    templateContext:
      mb:
        signing:
          enabled: true
          zipSources: false
          ${{ if parameters.RealSign }}:
            signType: real
          ${{ else }}:
            signType: test
        sbom:
          enabled: true
        localization:
          enabled: ${{ parameters.EnableLocalization }}
          ${{ if eq(variables['Build.Reason'], 'pullRequest') }}:
            languages: ENU,JPN
        optprof:
          enabled: ${{ parameters.EnableOptProf }}
          ProfilingInputsDropName: $(ProfilingInputsDropName)
          OptimizationInputsLookupMethod: DropPrefix
          DropNamePrefix: OptimizationInputs/$(System.TeamProject)/$(Build.Repository.Name)
          ShouldSkipOptimize: ${{ parameters.ShouldSkipOptimize }}
          AccessToken: $(System.AccessToken)
        mbpresteps:
        - checkout: self
          fetchDepth: 0 # avoid shallow clone so nbgv can do its work.
          clean: true
        - ${{ if parameters.EnableOptProf }}:
          - powershell: Write-Host "##vso[task.setvariable variable=PROFILINGINPUTSDROPNAME]$(azure-pipelines/variables/ProfilingInputsDropName.ps1)"
            displayName: âš™ Set ProfilingInputsDropName for optprof

      outputParentDirectory: $(Build.ArtifactStagingDirectory)
      outputs:
      - ${{ each artifact_name in parameters.artifact_names }}:
        - ${{ if or(ne(artifact_name, 'testResults'), parameters.RunTests) }}:
          - output: pipelineArtifact
            displayName: ðŸ“¢ Publish ${{ artifact_name }}-Windows
            targetPath: $(Build.ArtifactStagingDirectory)/${{ artifact_name }}-Windows
            artifactName: ${{ artifact_name }}-Windows
            condition: succeededOrFailed()
      - output: pipelineArtifact
        displayName: ðŸ“¢ Publish VSInsertion-Windows
        targetPath: $(Build.ArtifactStagingDirectory)/VSInsertion-Windows
        artifactName: VSInsertion-Windows
      - ${{ if parameters.EnableLocalization }}:
        - output: pipelineArtifact
          displayName: ðŸ“¢ Publish LocBin-Windows
          targetPath: $(Build.ArtifactStagingDirectory)/LocBin-Windows
          artifactName: LocBin-Windows
      - ${{ if and(parameters.EnableCompliance, parameters.EnableAPIScan, ne(variables['Build.Reason'], 'pullRequest')) }}:
        - output: pipelineArtifact
          displayName: ðŸ“¢ Publish APIScanInputs
          targetPath: $(Build.ArtifactStagingDirectory)/APIScanInputs-Windows
          artifactName: APIScanInputs
  steps:
  - ${{ if not(parameters.Is1ESPT) }}:
    - checkout: self
      fetchDepth: 0 # avoid shallow clone so nbgv can do its work.
      clean: true
    - ${{ if parameters.EnableOptProf }}:
      - powershell: Write-Host "##vso[task.setvariable variable=PROFILINGINPUTSDROPNAME]$(azure-pipelines/variables/ProfilingInputsDropName.ps1)"
        displayName: âš™ Set ProfilingInputsDropName for optprof

  - ${{ if eq(variables['Build.Reason'], 'Schedule') }}:
    - template: schedule-only-steps.yml

  - template: install-dependencies.yml

  - script: dotnet nbgv cloud -ca
    displayName: âš™ Set build number
    name: nbgv

  - ${{ if eq(variables['system.collectionId'], '011b8bdf-6d56-4f87-be0d-0092136884d9') }}:
    - template: microbuild.before.yml
      parameters:
        EnableLocalization: ${{ parameters.EnableLocalization }}
        EnableOptProf: ${{ parameters.EnableOptProf }}
        IsOptProf: ${{ parameters.IsOptProf }}
        ShouldSkipOptimize: ${{ parameters.ShouldSkipOptimize }}
        RealSign: ${{ parameters.RealSign }}

  - template: dotnet.yml
    parameters:
      Is1ESPT: ${{ parameters.Is1ESPT }}
      RunTests: ${{ parameters.RunTests }}
      IsOptProf: ${{ parameters.IsOptProf }}

  - ${{ if and(parameters.EnableDotNetFormatCheck, not(parameters.EnableLinuxBuild)) }}:
    - script: dotnet format --verify-no-changes --no-restore
      displayName: ðŸ’… Verify formatted code

  - ${{ if eq(variables['system.collectionId'], '011b8bdf-6d56-4f87-be0d-0092136884d9') }}:
    - template: microbuild.after.yml
      parameters:
        EnableOptProf: ${{ parameters.EnableOptProf }}
        IsOptProf: ${{ parameters.IsOptProf }}

  - template: expand-template.yml

- ${{ if not(parameters.IsOptProf) }}:
  - ${{ if parameters.EnableLinuxBuild }}:
    - job: Linux
      pool: ${{ parameters.linuxPool }}
      ${{ if eq(variables['system.collectionId'], '011b8bdf-6d56-4f87-be0d-0092136884d9') }}:
        templateContext:
          mb:
            ${{ if parameters.RealSign }}:
              signing:
                enabled: false # enable when building unique artifacts on this agent that must be signed
                signType: real
          outputParentDirectory: $(Build.ArtifactStagingDirectory)
          outputs:
          - ${{ each artifact_name in parameters.artifact_names }}:
            - ${{ if or(ne(artifact_name, 'testResults'), parameters.RunTests) }}:
              - output: pipelineArtifact
                displayName: ðŸ“¢ Publish ${{ artifact_name }}-Linux
                targetPath: $(Build.ArtifactStagingDirectory)/${{ artifact_name }}-Linux
                artifactName: ${{ artifact_name }}-Linux
                condition: succeededOrFailed()
      steps:
      - checkout: self
        fetchDepth: 0 # avoid shallow clone so nbgv can do its work.
        clean: true
      - template: install-dependencies.yml
      - template: dotnet.yml
        parameters:
          Is1ESPT: ${{ parameters.Is1ESPT }}
          RunTests: ${{ parameters.RunTests }}
      - ${{ if parameters.EnableDotNetFormatCheck }}:
        - script: dotnet format --verify-no-changes --no-restore
          displayName: ðŸ’… Verify formatted code
      - template: expand-template.yml

  - ${{ if parameters.EnableMacOSBuild }}:
    - job: macOS
      pool: ${{ parameters.macOSPool }}
      ${{ if eq(variables['system.collectionId'], '011b8bdf-6d56-4f87-be0d-0092136884d9') }}:
        templateContext:
          mb:
            ${{ if parameters.RealSign }}:
              signing:
                enabled: false # enable when building unique artifacts on this agent that must be signed
                signType: real
          outputParentDirectory: $(Build.ArtifactStagingDirectory)
          outputs:
          - ${{ each artifact_name in parameters.artifact_names }}:
            - ${{ if or(ne(artifact_name, 'testResults'), parameters.RunTests) }}:
              - output: pipelineArtifact
                displayName: ðŸ“¢ Publish ${{ artifact_name }}-macOS
                targetPath: $(Build.ArtifactStagingDirectory)/${{ artifact_name }}-macOS
                artifactName: ${{ artifact_name }}-macOS
                condition: succeededOrFailed()
      steps:
      - checkout: self
        fetchDepth: 0 # avoid shallow clone so nbgv can do its work.
        clean: true
      - template: install-dependencies.yml
      - template: dotnet.yml
        parameters:
          Is1ESPT: ${{ parameters.Is1ESPT }}
          RunTests: ${{ parameters.RunTests }}
      - template: expand-template.yml

  - job: WrapUp
    dependsOn:
    - Windows
    - ${{ if parameters.EnableLinuxBuild }}:
      - Linux
    - ${{ if parameters.EnableMacOSBuild }}:
      - macOS
    pool: ${{ parameters.windowsPool }} # Use Windows agent because PublishSymbols task requires it (https://github.com/microsoft/azure-pipelines-tasks/issues/13821).
    condition: succeededOrFailed()
    steps:
    - checkout: self
      fetchDepth: 0 # avoid shallow clone so nbgv can do its work.
      clean: true
    - template: install-dependencies.yml
      parameters:
        initArgs: -NoRestore
    - template: publish-symbols.yml
      parameters:
        EnableLinuxBuild: ${{ parameters.EnableLinuxBuild }}
        EnableMacOSBuild: ${{ parameters.EnableMacOSBuild }}
    - ${{ if parameters.RunTests }}:
      - template: publish-codecoverage.yml
        parameters:
          EnableLinuxBuild: ${{ parameters.EnableLinuxBuild }}
          EnableMacOSBuild: ${{ parameters.EnableMacOSBuild }}

  - ${{ if and(parameters.EnableCompliance, parameters.EnableAPIScan, ne(variables['Build.Reason'], 'pullRequest')) }}:
    - template: apiscan.yml
      parameters:
        windowsPool: ${{ parameters.windowsPool }}
