steps:
- powershell: |
    "$env:userprofile\.nuget\packages", "$env:LocalAppData\NuGet\Cache", "$env:AppData\tsd-cache" |% {
      if (Test-Path $_) { Remove-Item $_ -Recurse -Force }
    }
  displayName: Purge package caches
  condition: and(succeeded(), eq(variables['system.collectionId'], '011b8bdf-6d56-4f87-be0d-0092136884d9'))
