steps:
- script: |
    dotnet build-server shutdown
    git clean -fdx
  displayName: ðŸ§¹ Cleaning repo for template expansion
- powershell: |
    git config user.name "test user"
    git config user.email "andrewarnott@gmail.com"
    ./Expand-Template.ps1 -LibraryName Calc -Author "Andrew Arnott"
  displayName: ðŸ§ª Expanding template
  failOnStderr: true
# TODO: Verify that all changes are staged to the git index
- script: dotnet build
  displayName: ðŸ›  dotnet build (expanded template)
