parameters:
  initArgs:

steps:

- powershell: |
    .\init.ps1 -AccessToken '$(System.AccessToken)' ${{ parameters['initArgs'] }} -UpgradePrerequisites
    dotnet --info
  displayName: Install prerequisites

- task: PowerShell@2
  inputs:
    filePath: azure-pipelines/variables/_pipelines.ps1
    failOnStderr: true
  displayName: Set pipeline variables based on source
