parameters:
- name: EnableLocalization
  type: boolean
  default: false
- name: EnableOptProf
  type: boolean
  default: false
- name: IsOptProf
  type: boolean
  default: false
- name: ShouldSkipOptimize
  type: boolean
  default: false
- name: RealSign
  type: boolean

steps:
- ${{ if and(not(parameters.IsOptProf), ne(variables['Build.Reason'], 'PullRequest')) }}:
  # notice@0 requires CG detection to run first, and non-default branches don't inject it automatically.
  - ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    - task: ComponentGovernanceComponentDetection@0
      displayName: üîç Component Detection

  - task: notice@0
    displayName: üõ†Ô∏è Generate NOTICE file
    inputs:
      outputfile: $(System.DefaultWorkingDirectory)/obj/NOTICE
      outputformat: text
    retryCountOnTaskFailure: 3 # fails when the cloud service is overloaded
    continueOnError: ${{ not(parameters.RealSign) }} # Tolerate failures when we're not building something that may ship.

- ${{ if parameters.IsOptProf }}:
  # We have to install these plugins ourselves for Optprof runs because those pipelines haven't migrated to 1ES PT yet.
  - task: MicroBuildOptProfPlugin@6
    inputs:
      ProfilingInputsDropName: $(ProfilingInputsDropName)
      OptimizationInputsLookupMethod: DropPrefix
      DropNamePrefix: OptimizationInputs/$(System.TeamProject)/$(Build.Repository.Name)
      ShouldSkipOptimize: ${{ parameters.ShouldSkipOptimize }}
      AccessToken: $(System.AccessToken)
    displayName: üîß Install OptProf Plugin

  - task: MicroBuildSigningPlugin@4
    inputs:
      signType: Real
      zipSources: false
    displayName: üîß Install MicroBuild Signing Plugin

  - ${{ if parameters.EnableLocalization }}:
    - task: MicroBuildLocalizationPlugin@4
      inputs:
        languages: $(LocLanguages)
      displayName: üîß Install MicroBuild Localization Plugin
