steps:
- task: ComponentGovernanceComponentDetection@0
  displayName: Component Detection

- task: notice@0
  displayName: Generate NOTICE file
  inputs:
    outputfile: $(System.DefaultWorkingDirectory)/obj/NOTICE
    outputformat: text

- task: MicroBuildSigningPlugin@3
  inputs:
    signType: $(SignType)
  displayName: Install MicroBuild Signing Plugin

- task: MicroBuildSbomPlugin@1
  displayName: Install MicroBuild Sbom Plugin
