parameters:
  includeMacOS:

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    artifact: symbols-Windows
    path: $(Pipeline.Workspace)/symbols/Windows
  displayName: Download Windows symbols
  continueOnError: true
- task: DownloadPipelineArtifact@2
  inputs:
    artifact: symbols-Linux
    path: $(Pipeline.Workspace)/symbols/Linux
  displayName: Download Linux symbols
  continueOnError: true
- task: DownloadPipelineArtifact@2
  inputs:
    artifact: symbols-macOS
    path: $(Pipeline.Workspace)/symbols/macOS
  displayName: Download macOS symbols
  continueOnError: true
  condition: ${{ parameters.includeMacOS }}

- task: DownloadPipelineArtifact@2
  inputs:
    artifact: test_symbols-Windows
    path: $(Pipeline.Workspace)/test_symbols/Windows
  displayName: Download Windows test symbols
  continueOnError: true
- task: DownloadPipelineArtifact@2
  inputs:
    artifact: test_symbols-Linux
    path: $(Pipeline.Workspace)/test_symbols/Linux
  displayName: Download Linux test symbols
  continueOnError: true
- task: DownloadPipelineArtifact@2
  inputs:
    artifact: test_symbols-macOS
    path: $(Pipeline.Workspace)/test_symbols/macOS
  displayName: Download macOS test symbols
  continueOnError: true
  condition: ${{ parameters.includeMacOS }}

- task: PublishSymbols@2
  inputs:
    SymbolsFolder: $(Pipeline.Workspace)/symbols
    SearchPattern: '**/*.pdb'
    IndexSources: false
    SymbolServerType: TeamServices
  displayName: Publish symbols

- task: PublishSymbols@2
  inputs:
    SymbolsFolder: $(Pipeline.Workspace)/test_symbols
    SearchPattern: '**/*.pdb'
    IndexSources: false
    SymbolServerType: TeamServices
  displayName: Publish test symbols
