steps:
- download: current
  artifact: coverageResults-Windows
  displayName: ðŸ”» Download Windows code coverage results
  continueOnError: true
#- powershell: azure-pipelines/Merge-CodeCoverage.ps1 -Path '$(Pipeline.Workspace)' -OutputFile coveragereport/merged.cobertura.xml -Format Cobertura -Verbose
#  displayName: âš™ Merge coverage
#- task: PublishCodeCoverageResults@2
#  displayName: ðŸ“¢ Publish code coverage results to Azure DevOps
#  inputs:
#    summaryFileLocation: coveragereport/merged.cobertura.xml
#    failIfCoverageEmpty: true
