parameters:
  includeMacOS:

steps:
- download: current
  artifact: coverageResults-Windows
  displayName: ðŸ”» Download Windows code coverage results
  continueOnError: true
- download: current
  artifact: coverageResults-Linux
  displayName: ðŸ”» Download Linux code coverage results
  continueOnError: true
- download: current
  artifact: coverageResults-macOS
  displayName: ðŸ”» Download macOS code coverage results
  continueOnError: true
  condition: ${{ parameters.includeMacOS }}
- powershell: |
    dotnet tool install --tool-path obj dotnet-reportgenerator-globaltool --version 5.1.9 --configfile azure-pipelines/justnugetorg.nuget.config
    Copy-Item -Recurse $(Pipeline.Workspace)/coverageResults-Windows/obj/* $(System.DefaultWorkingDirectory)/obj
    Write-Host 'Substituting {reporoot} with $(System.DefaultWorkingDirectory)'
    $reports = Get-ChildItem -Recurse '$(Pipeline.Workspace)/*.cobertura.xml'
    $reports |% {
        $content = Get-Content -Path $_ |% { $_.Replace('{reporoot}', '$(System.DefaultWorkingDirectory)') }
        Set-Content -Path $_ -Value $content -Encoding UTF8
    }

    $Inputs = [string]::join(';', ($reports |% { Resolve-Path -relative $_ }))
    obj/reportgenerator -reports:"$Inputs" -targetdir:coveragereport -reporttypes:Cobertura
  displayName: âš™ Merge coverage
- task: PublishCodeCoverageResults@1
  displayName: ðŸ“¢ Publish code coverage results to Azure DevOps
  inputs:
    codeCoverageTool: cobertura
    summaryFileLocation: coveragereport/Cobertura.xml
    failIfCoverageEmpty: true
