steps:
- download: CI
  artifact: Variables-Windows
  displayName: ğŸ”» Download Variables-Windows artifact
- powershell: $(Pipeline.Workspace)/CI/Variables-Windows/_define.ps1
  displayName: âš™ï¸ Set pipeline variables based on artifacts
