parameters:
  EnableAPIScan:

steps:

- powershell: echo "##vso[build.addbuildtag]compliance"
  displayName: ğŸ·ï¸ Tag run with 'compliance'

- task: CredScan@3
  displayName: ğŸ” Run CredScan

- task: PoliCheck@2
  displayName: ğŸ” Run PoliCheck
  inputs:
    targetType: F
    targetArgument: $(System.DefaultWorkingDirectory)
    optionsUEPATH: $(System.DefaultWorkingDirectory)\azure-pipelines\PoliCheckExclusions.xml

- task: CopyFiles@2
  displayName: ğŸ“‚ Collect APIScan/BinSkim inputs
  inputs:
    SourceFolder: $(Build.ArtifactStagingDirectory)/Symbols-$(Agent.JobName)
    # Exclude any patterns from the Contents (e.g. `!**/git2*`) that we have symbols for but do not need to run APIScan on.
    Contents: |
      **
      !**/arm64/**
      !**/win-arm64/**
      !**/linux-*/**
      !**/osx*/**
    TargetFolder: $(Build.ArtifactStagingDirectory)/APIScanInputs

- task: BinSkim@4
  displayName: ğŸ” Run BinSkim
  inputs:
    InputType: Basic
    Function: analyze
    TargetPattern: guardianGlob
    AnalyzeTargetGlob: $(Build.ArtifactStagingDirectory)/APIScanInputs/**/*.dll;$(Build.ArtifactStagingDirectory)/APIScanInputs/**/*.exe

- task: APIScan@2
  displayName: ğŸ” Run APIScan
  inputs:
    softwareFolder: $(Build.ArtifactStagingDirectory)/APIScanInputs
    softwareName: $(SymbolsFeatureName)
    softwareVersionNum: $(NBGV_MajorMinorVersion)
    isLargeApp: false
    toolVersion: Latest
  condition: and(succeeded(), ${{ parameters.EnableAPIScan }}, ne(variables.ApiScanClientId, ''))
  env:
    AzureServicesAuthConnectionString: runAs=App;AppId=$(ApiScanClientId)

- task: SdtReport@2
  displayName: ğŸ“ƒ Create Security Analysis Report
  inputs:
    GdnExportAllTools: true

- task: PublishSecurityAnalysisLogs@3
  displayName: ğŸ“¢ Publish Code Analysis Logs
  inputs:
    ArtifactName: CodeAnalysisLogs
    ArtifactType: Container
    PublishProcessedResults: true
    AllTools: true
    ToolLogsNotFoundAction: Standard

- task: PostAnalysis@2
  displayName: ğŸ‹ï¸â€â™€ï¸ Break on compliance issues
  inputs:
    GdnBreakAllTools: true
    GdnBreakGdnToolBinSkimSeverity: Warning
    GdnBreakSuppressionFiles: $(System.DefaultWorkingDirectory)/azure-pipelines/falsepositives.gdnsuppress
    GdnBreakSuppressionSets: falsepositives
    GdnBreakOutputSuppressionFile: $(Build.ArtifactStagingDirectory)/guardian_failures_as_suppressions/
    GdnBreakOutputSuppressionSet: falsepositives

# This is useful when false positives appear so we can copy some of the output into the suppressions file.
- publish: $(Build.ArtifactStagingDirectory)/guardian_failures_as_suppressions
  artifact: guardian_failures_as_suppressions
  displayName: ğŸ” Publish Guardian failures
  condition: failed()
