parameters:
- name: deadPATServiceConnectionId # The GUID of the PAT-based service connection whose access token must be replaced.
  type: string
- name: wifServiceConnectionName # The name of the WIF service connection to use to get the access token.
  type: string
- name: resource # The scope for which the access token is requested.
  type: string
  default: 499b84ac-1321-427f-aa17-267ca6975798 # Azure Artifact feeds (any of them)

steps:
- task: AzureCLI@2
  displayName: üîè Authenticate with WIF service connection
  inputs:
    azureSubscription: ${{ parameters.wifServiceConnectionName }}
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: |
      $accessToken = az account get-access-token --query accessToken --resource '${{ parameters.resource }}' -o tsv
      # Set the access token as a secret, so it doesn't get leaked in the logs
      Write-Host "##vso[task.setsecret]$accessToken"
      # Override the apitoken of the nuget service connection, for the duration of this stage
      Write-Host "##vso[task.setendpoint id=${{ parameters.deadPATServiceConnectionId }};field=authParameter;key=apitoken]$accessToken"
